controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_agb:
    path: /agb
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController
    defaults:
        template: agb/index.html.twig
